server:
  port: 80

spring:
  datasource:
    username: ${username}
    password: ${password}
    url: ${jdbcUrl}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${gmailPassword}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  application:
    name: database
