server:
  port: 80

spring:
  config:
    import:
    - vault://
  cloud:
    vault:
      kv:
        enabled: true
      scheme: http
      authentication: token
      token:
  datasource:
    username:
    password:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  application:
    name: database
